### ISSUE TITLE
TypeError: add() got an unexpected keyword argument 'storage'

### ISSUE THREAD

**Issue by seman** [jenkinsci/jenkins-charm#32]
Unit tests fail as seems here:

```
ERROR: setUpClass (__main__.XenialNRPEDeploymentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/cwr-tmp-K9BH2m/bundletester-M3dg9T/jenkins/tests/deployment.py", line 37, in setUpClass
    cls.spec.deploy()
  File "/tmp/cwr-tmp-K9BH2m/bundletester-M3dg9T/jenkins/tests/deployment.py", line 15, in deploy
    self._run_hooks("pre_setup")
  File "/tmp/cwr-tmp-K9BH2m/bundletester-M3dg9T/jenkins/tests/deployment.py", line 27, in _run_hooks
    getattr(self, attribute)()
  File "/tmp/cwr-tmp-K9BH2m/bundletester-M3dg9T/jenkins/tests/basic.py", line 55, in _pre_setup_00_basic
    storage={"jenkins": "rootfs,50M"})
TypeError: add() got an unexpected keyword argument 'storage'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
```

http://cwr.vapour.ws/jenkins/5ed85bd481754323908e9a878fa3b725/report.html

**Comment by lutostag** [comment]
Looks like the pypi version of amulet does not have storage capabilities. This is an upstream issue, but we may want to point at the git version for pip depending on response there.

**Comment by lutostag** [comment]
Fixed upstream with a release.
