### ISSUE TITLE
Jenkins master fails to install due to missing initialAdminPassword file

### ISSUE THREAD

**Issue by kvalev** [jenkinsci/jenkins-charm#40]
When installing the Jenkins master via `juju deploy jenkins`, it fails with the following log:

```
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.juju-log Invoking reactive handler: reactive/jenkins.py:109:configure_admin
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.juju-log maintenance: Configuring Jenkins public url
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.juju-log Writing file /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml jenkins:nogroup 444
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.juju-log maintenance: Configuring admin user
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.juju-log Configuring user for jenkins
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached Traceback (most recent call last):
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/var/lib/juju/agents/unit-jenkins-0/charm/hooks/jenkins-storage-attached", line 19, in <module>
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     main()
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     bus.dispatch()
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     _invoke(other_handlers)
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     handler.invoke()
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     self._action(*args)
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/var/lib/juju/agents/unit-jenkins-0/charm/reactive/jenkins.py", line 126, in configure_admin
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     users.configure_admin()
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "lib/charms/layer/jenkins/users.py", line 21, in configure_admin
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     api.update_password(admin.username, admin.password)
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "lib/charms/layer/jenkins/api.py", line 56, in update_password
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     client = self._make_client()
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "/usr/local/lib/python3.5/dist-packages/charmhelpers/core/decorators.py", line 40, in _retry_on_exception_inner_2
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     return f(*args, **kwargs)
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "lib/charms/layer/jenkins/api.py", line 127, in _make_client
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     client = jenkins.Jenkins(self.url, user, creds.password())
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "lib/charms/layer/jenkins/credentials.py", line 27, in password
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     return self._initial_password()
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached   File "lib/charms/layer/jenkins/credentials.py", line 49, in _initial_password
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached     with open(paths.INITIAL_PASSWORD) as fd:
unit-jenkins-0: 19:18:16 INFO unit.jenkins/0.jenkins-storage-attached FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/jenkins/secrets/initialAdminPassword'
unit-jenkins-0: 19:18:16 ERROR juju.worker.uniter.operation hook "jenkins-storage-attached" failed: exit status 1
```

**Comment by kvalev** [comment]
The root cause seems to be the `jenkins-config.xml` configuration - [in case there is a configured security realm, Jenkins does not create the initialAdminPassword file](https://github.com/jenkinsci/jenkins/blob/ae1fdc95a1d50df65a97447ff536d21cb2c5dba2/core/src/main/java/jenkins/install/SetupWizard.java#L102) and the Charm deployment fails

**Comment by chintu481** [comment]
[root@ip-172-31-89-166 jenkins]# /root/.jenkins/secrets/initialAdminPassword
-bash: /root/.jenkins/secrets/initialAdminPassword: Permission denied




What the reason?
i cannot find jenkins.log file for password

**Comment by jamesbeedy** [comment]
this is https://github.com/jenkinsci/jenkins-charm/issues/47

**Comment by mthaddon** [comment]
Closing this out, as #47 is now resolved.
